-- Create proper bronze table structure to match Databricks exactly
-- This will ensure the ETL produces identical results

-- Drop existing bronze table if it exists
DROP TABLE IF EXISTS POC.PUBLIC.NCP_BRONZE;

-- Create new bronze table with exact Databricks structure
CREATE TABLE POC.PUBLIC.NCP_BRONZE (
    transaction_main_id STRING,
    transaction_date TIMESTAMP_NTZ,
    transaction_id_life_cycle STRING,
    transaction_date_life_cycle TIMESTAMP_NTZ,
    transaction_type_id STRING,
    transaction_type STRING,
    transaction_result_id STRING,
    final_transaction_status STRING,
    threed_flow_status STRING,
    challenge_preference STRING,
    preference_reason STRING,
    authentication_flow STRING,
    threed_flow STRING,
    is_void STRING,
    liability_shift STRING,
    status STRING,
    acs_url STRING,
    acs_res_authentication_status STRING,
    r_req_authentication_status STRING,
    transaction_status_reason STRING,
    interaction_counter STRING,
    challenge_cancel STRING,
    three_ds_method_indication STRING,
    is_sale_3d STRING,
    manage_3d_decision STRING,
    decline_reason STRING,
    amount_in_usd STRING,
    approved_amount_in_usd STRING,
    original_currency_amount STRING,
    rate_usd STRING,
    currency_code STRING,
    three_ds_protocol_version STRING,
    is_external_mpi STRING,
    rebill STRING,
    device_channel STRING,
    user_agent_3d STRING,
    device_type STRING,
    device_name STRING,
    device_os STRING,
    challenge_window_size STRING,
    type_of_authentication_method STRING,
    multi_client_id STRING,
    client_id STRING,
    multi_client_name STRING,
    client_name STRING,
    industry_code STRING,
    credit_card_id STRING,
    cccid STRING,
    bin STRING,
    is_prepaid STRING,
    card_scheme STRING,
    card_type STRING,
    consumer_id STRING,
    issuer_bank_name STRING,
    device_channel_name STRING,
    bin_country STRING,
    is_eea STRING,
    region STRING,
    payment_instrument STRING,
    source_application STRING,
    is_partial_amount STRING,
    enable_partial_approval STRING,
    partial_approval_is_void STRING,
    partial_approval_void_id STRING,
    partial_approval_void_time STRING,
    partial_approval_requested_amount STRING,
    partial_approval_requested_currency STRING,
    partial_approval_processed_amount STRING,
    partial_approval_processed_currency STRING,
    partial_approval_processed_amount_in_usd STRING,
    website_id STRING,
    browser_user_agent STRING,
    ip_country STRING,
    processor_id STRING,
    processor_name STRING,
    risk_email_id STRING,
    is_currency_converted STRING,
    email_seniority_start_date STRING,
    email_payment_attempts STRING,
    final_fraud_decision_id STRING,
    external_token_eci STRING,
    risk_threed_eci STRING,
    threed_eci STRING,
    cvv_code STRING,
    provider_response_code STRING,
    issuer_card_program_id STRING,
    scenario_id STRING,
    previous_id STRING,
    next_id STRING,
    step STRING,
    reprocess_3d_reason STRING,
    data_only_authentication_result STRING,
    is_cascaded_after_data_only_authentication STRING,
    next_action STRING,
    authentication_method STRING,
    cavv_verification_code STRING,
    channel STRING,
    authentication_request STRING,
    authentication_response STRING,
    cc_hash STRING,
    exp_date STRING,
    message_version_3d STRING,
    cc_seniority_start_date STRING,
    mc_scheme_token_used STRING,
    inserted_at TIMESTAMP_NTZ,
    stored_credentials_mode STRING,
    avs_code STRING,
    is_3d STRING,
    credit_type_id STRING,
    subscription_step STRING,
    scheme_token_fetching_result STRING,
    browser_screen_height STRING,
    browser_screen_width STRING,
    filter_reason_id STRING,
    reason_code STRING,
    reason STRING,
    request_timestamp_service STRING,
    token_unique_reference_service STRING,
    response_timestamp_service STRING,
    api_type_service STRING,
    request_timestamp_fetching STRING,
    token_unique_reference_fetching STRING,
    response_timestamp_fetching STRING,
    api_type_fetching STRING,
    is_cryptogram_fetching_skipped STRING,
    is_external_scheme_token STRING,
    three_ds_server_trans_id STRING,
    gateway_id STRING,
    cc_request_type_id STRING,
    upo_id STRING,
    iscardReplaced STRING,
    isvdcuFeeApplied STRING,
    aftType STRING,
    secondarycccid STRING,
    transaction_duration STRING,
    authorization_req_duration STRING,
    firstInstallment STRING,
    periodicalInstallment STRING,
    numberOfInstallments STRING,
    installmentProgram STRING,
    installmentFundingType STRING,
    first_installment_usd STRING,
    periodical_installment_usd STRING,
    applicableScenarios STRING,
    cascading_ab_test_experimant_name STRING,
    -- Keep raw line for debugging
    raw_line STRING
);

-- Insert sample data from your provided data for testing
INSERT INTO POC.PUBLIC.NCP_BRONZE (
    transaction_main_id, transaction_date, transaction_id_life_cycle, transaction_date_life_cycle,
    transaction_type_id, transaction_type, transaction_result_id, final_transaction_status,
    threed_flow_status, challenge_preference, preference_reason, authentication_flow,
    threed_flow, is_void, liability_shift, status, acs_url, acs_res_authentication_status,
    r_req_authentication_status, transaction_status_reason, interaction_counter, challenge_cancel,
    three_ds_method_indication, is_sale_3d, manage_3d_decision, decline_reason,
    amount_in_usd, approved_amount_in_usd, original_currency_amount, rate_usd, currency_code,
    three_ds_protocol_version, is_external_mpi, rebill, device_channel, user_agent_3d,
    device_type, device_name, device_os, challenge_window_size, type_of_authentication_method,
    multi_client_id, client_id, multi_client_name, client_name, industry_code,
    credit_card_id, cccid, bin, is_prepaid, card_scheme, card_type, consumer_id,
    issuer_bank_name, device_channel_name, bin_country, is_eea, region,
    payment_instrument, source_application, website_id, browser_user_agent, ip_country,
    processor_id, processor_name, risk_email_id, is_currency_converted, email_seniority_start_date,
    email_payment_attempts, final_fraud_decision_id, external_token_eci, risk_threed_eci,
    threed_eci, cvv_code, provider_response_code, issuer_card_program_id, scenario_id,
    previous_id, next_id, step, reprocess_3d_reason, data_only_authentication_result,
    is_cascaded_after_data_only_authentication, next_action, authentication_method,
    cavv_verification_code, channel, authentication_request, authentication_response,
    cc_hash, exp_date, message_version_3d, cc_seniority_start_date, mc_scheme_token_used,
    inserted_at, stored_credentials_mode, avs_code, is_3d, credit_type_id,
    subscription_step, scheme_token_fetching_result, browser_screen_height, browser_screen_width,
    filter_reason_id, reason_code, reason, request_timestamp_service, token_unique_reference_service,
    response_timestamp_service, api_type_service, request_timestamp_fetching, token_unique_reference_fetching,
    response_timestamp_fetching, api_type_fetching, is_cryptogram_fetching_skipped, is_external_scheme_token,
    three_ds_server_trans_id, gateway_id, cc_request_type_id, upo_id, iscardReplaced,
    isvdcuFeeApplied, aftType, secondarycccid, transaction_duration, authorization_req_duration,
    firstInstallment, periodicalInstallment, numberOfInstallments, installmentProgram,
    installmentFundingType, first_installment_usd, periodical_installment_usd, applicableScenarios,
    cascading_ab_test_experimant_name, raw_line
) VALUES
('1120000003007353988', '2025-02-25T13:29:30.003', '1120000003007353845', '2025-02-25T13:29:29.067', 
 '1007', 'Auth', '1008', '0', null, 'no_preference', '0', null, null, 'No', '0', null, 
 null, null, null, null, null, null, null, '1', '0', 'Do not honor', '14.76', null, 
 '147.0000', '.100379', 'MAD', '2', '0', '0', null, 'deprecated', '4', null, null, null, 
 null, '151002671', '251003570', 'Whaleco Technology Ltd Multi', 'Whaleco Technology Ltd - RAF', 
 '5399', '1120000000253726071', '2', '532196', '0', 'MasterCard', 'Credit', '253948502', 
 'CREDIT IMMOBILIER ET. HOTELIER', null, 'ma', '0', 'Africa', 'CC', 'SafeCharge REST API', 
 '280676', null, null, '99', 'Nuvei Acquirer - MasterCard', '0', '0', '2012-06-13T11:57:56.653', 
 '0', '3', null, '4', null, ' ', '05', 'MCC', '13', '-1', '1120000003007354258', '0', 
 null, '1', '0', null, null, null, '1', 'deprecated', 'deprecated', 
 '1692DA696C8DEFBCB037B183828F1B89A02BC32D', '1128-01-01T00:00:00.000', null, '-', 
 '1', '2025-02-26T12:12:06.649', '1', ' ', '0', '0', null, 'ACTIVE', null, null, null, 
 null, null, '2025-02-25 13:29:30.5466667', 'DM4MMC1MA00000003c110b26ad3f43ffb2037ddf6555e70c', 
 '2025-02-25 13:29:30.5500000', '1', null, null, null, null, null, '0', null, 
 '1120000003007353845', '2', '6249839728', '0', '0', null, null, '2042', 'deprecated', 
 null, null, null, null, null, null, null, '13,14,20', null, 'raw_line_placeholder'),
 
('1120000003007353989', '2025-02-25T13:29:30.003', '1120000003007353885', '2025-02-25T13:29:29.300', 
 '1019', 'Auth3D', '1006', '1', null, 'no_preference', '12', null, null, 'No', '0', null, 
 null, null, null, null, null, null, null, '1', '1', ' ', '366.60', null, '350.0000', 
 '1.047425', 'EUR', '2', '0', '0', null, 'deprecated', '1', 'Generic Android 2.0', 
 'Android 2.0', null, null, '251003332', '251003333', 'ACE Europe Sp. Z o.o. Multi', 
 'ACE Europe Sp. Z o.o.', '4829', '2130000000792360389', '1', '441029', '0', 'Visa', 
 'Debit', '1120000000571275744', 'Piraeus Bank S.A.', null, 'gr', '1', 'West Europe', 
 'CC', 'Web Cashier', '278486', null, null, '103', 'Nuvei Acquirer - Visa', null, '0', 
 '-', null, null, null, null, null, ' ', ' ', 'VIS', null, null, null, null, null, null, 
 '0', '1', null, null, '1', 'deprecated', 'deprecated', '2D0CFB603771686CB0B434E548CBAFDAC4E8DF35', 
 '0327-01-01T00:00:00.000', null, '2025-02-25T13:30:55.450', '0', '2025-02-26T12:12:06.649', 
 '1', ' ', '0', '0', null, null, null, null, null, null, null, null, null, null, null, 
 null, null, null, null, null, '0', null, '1120000003007353885', '2', '5132389148', '0', 
 '0', null, null, '1534', 'deprecated', null, null, null, null, null, null, null, null, 
 null, 'raw_line_placeholder'),
 
('1120000003007353990', '2025-02-25T13:29:30.013', '1120000003007352063', '2025-02-25T13:29:15.600', 
 '1006', 'Settle', '1006', '1', null, null, null, null, null, 'No', '0', null, null, 
 null, null, null, null, null, null, '0', '0', ' ', '2.53', '2.53', '2.0000', '1.263421', 
 'GBP', null, '0', '0', null, 'deprecated', '4', null, null, null, null, '251001439', 
 '251001440', 'Curve UK Limited Multi', 'Curve UK- 5411', '5411', '2130000000820289381', 
 '2', '537410', '0', 'MasterCard', 'Debit', '2130000000687915409', 'NATIONAL WESTMINSTER BANK PLC ', 
 null, 'gb', '1', 'West Europe', 'CC', 'SafeCharge REST API', '254398', null, null, 
 '99', 'Nuvei Acquirer - MasterCard', null, '0', '-', null, null, null, null, null, 
 ' ', ' ', 'DMC', null, null, null, null, null, null, null, null, null, null, '1', 
 'deprecated', 'deprecated', '7998FEA782BB9F26D46271E9F9D1962542E12A78', '0928-01-01T00:00:00.000', 
 null, '2024-10-05T17:47:23.010', '1', '2025-02-26T12:12:06.649', null, ' ', '0', '0', 
 null, 'ACTIVE', null, null, null, null, null, '2025-02-25 13:29:30.0433333', 
 'DM4MMC1GB00000009efc368837454dd79dde35e750219fc1', '2025-02-25 13:29:30.0466667', '1', 
 null, null, null, null, '1', '0', null, '1120000003007352063', '2', '0', '0', '0', 
 null, null, '89', 'deprecated', null, null, null, null, null, null, null, null, null, 'raw_line_placeholder');

-- Verify the structure
SELECT 'Bronze table created with' AS status, COUNT(*) AS row_count FROM POC.PUBLIC.NCP_BRONZE;

-- Show sample data to verify structure
SELECT 
    transaction_main_id,
    transaction_type, 
    multi_client_name,
    authentication_flow,
    threed_flow_status,
    inserted_at
FROM POC.PUBLIC.NCP_BRONZE 
LIMIT 3;
